# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiceSimulatorUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(317, 219)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 0, 0, 1, 1)
        self.spinBoxDices = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxDices.setFont(font)
        self.spinBoxDices.setObjectName("spinBoxDices")
        self.gridLayout.addWidget(self.spinBoxDices, 0, 2, 1, 1)
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 1, 0, 1, 2)
        self.spinBoxThrows = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxThrows.setFont(font)
        self.spinBoxThrows.setObjectName("spinBoxThrows")
        self.gridLayout.addWidget(self.spinBoxThrows, 1, 2, 1, 1)
        self.line1 = QtWidgets.QFrame(self.centralwidget)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.gridLayout.addWidget(self.line1, 2, 0, 1, 3)
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 3, 0, 1, 1)
        self.line2 = QtWidgets.QFrame(self.centralwidget)
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.gridLayout.addWidget(self.line2, 4, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonStart = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStart.setObjectName("buttonStart")
        self.horizontalLayout.addWidget(self.buttonStart)
        self.buttonStop = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStop.setObjectName("buttonStop")
        self.horizontalLayout.addWidget(self.buttonStop)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 3)
        self.lcdNumberDiceOutcome = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lcdNumberDiceOutcome.setFont(font)
        self.lcdNumberDiceOutcome.setObjectName("lcdNumberDiceOutcome")
        self.gridLayout.addWidget(self.lcdNumberDiceOutcome, 3, 1, 1, 2)
        self.label2.raise_()
        self.label3.raise_()
        self.spinBoxThrows.raise_()
        self.line1.raise_()
        self.label3.raise_()
        self.spinBoxThrows.raise_()
        self.label2.raise_()
        self.label1.raise_()
        self.lcdNumberDiceOutcome.raise_()
        self.line2.raise_()
        self.spinBoxDices.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dice Simulator"))
        self.label2.setText(_translate("MainWindow", "Number of dices"))
        self.label3.setText(_translate("MainWindow", "Dice throws per second"))
        self.label1.setText(_translate("MainWindow", "Current dice outcome:"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
        self.buttonStop.setText(_translate("MainWindow", "Stop"))

